### ISSUE TITLE
Unused expression in the non-function call case

### ISSUE THREAD

**Issue by NiKlimenko** [kwonoj/tslint-no-unused-expression-chai#9]
Hello, seems this case isn't handled by your library.
`e.should.have.property('response').to.be.undefined;`

TSLint: unused expression, expected an assignment or function call (no-unused-expression-chai)

**Comment by kwonoj** [comment]
This module supports for `expect` based assertion based on fn Call only. I was thinking of other type of assertion as well at the moment and there are sort of edge cases, decided not to.

**Comment by karfau** [comment]
@kwonoj Can you give me a hint where to start with trying to add support for `should`?
We are using a mixture of `expect` and `should` and disabling the rule on each occasion of `should` is annoying, but we also do not want to disable the complete rule...
I would love to contribute, but not sure what would be an approach that would like to land.
I could try to apply a second filter over the failures, like you did for `expect`.
But, since you mentioned it: what are those edge cases that made you decide not to?

**Comment by kwonoj** [comment]
what you may need is traverse AST via typescript compiler api (or some other means if you have). Most reason I decided not to support should assertion is it is not declarative syntax, as it is extended property chain to any object you'd like to assert and I found it could be more fragile than expect assertion verification.

**Comment by karfau** [comment]
But are you interested in case I find a solution that you consider stable enough?
And would you support me with understanding if I have a solution that doesn't work for you, why it doesn't?

**Comment by kwonoj** [comment]
You may feel freely either create your own packages or send out PR for those changes, if it have suffecient test cases also doesn't hurt performance too much, like having multiple / nested steps of AST validation. 

Unfortunately I am not much able to provide additional detail than currently I have shared as I'm quite much occupied with other daily work at this moment.
